name: avid_rt1_11M_2
group: avid_rt1_11M_2
#logdir: /host_home/avid
logdir: /workspace/

base_config_file: configs/train/dynamicrafter_512.yaml
action_config_file: configs/train/act_cond_diffusion_11M.yaml

target_module: ldwma.models.avid.AVIDAdapter
adapter_params:
  condition_adapter_on_base_outputs: True
  learnt_mask: True
  init_mask_bias: 0.0

data:
  target: ldwma.lightning.data_modules.rtx.RTXDataModule
  params:
    batch_size: 1
    target_height: 320
    target_width: 512
    dataset_name: "fractal20220817_data"
    shuffle_buffer: 100
    traj_len: 16
    train_split: "train[:5%]"
    val_split: "train[95%:96%]"

lightning:
  precision: 16
  trainer:
    strategy: ddp
    accelerator: "gpu"
    limit_train_batches: 800
    limit_val_batches: 4
    check_val_every_n_epoch: 5
    num_sanity_val_steps: 0
    num_nodes: 1
    benchmark: True
    accumulate_grad_batches: 8
    max_steps: 2000
    log_every_n_steps: 10
    gradient_clip_algorithm: "norm"
    gradient_clip_val: 1.0
    logger:
      target: pytorch_lightning.loggers.WandbLogger
      params:
        save_dir: /workspace/wandb/latent_diffusion/
        offline: False
        project: avid
        log_model: all
  callbacks:
    model_checkpoint:
      target: pytorch_lightning.callbacks.ModelCheckpoint
      params:
        filename: "{epoch}-{step}"
        save_weights_only: True
        every_n_train_steps: 250
        save_top_k: -1
        save_last: True
    batch_logger:
      target: lvdm.utils.callbacks.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 1
        log_images_kwargs:
          ddim_steps: 50
          unconditional_guidance_scale: 1.0
          timestep_spacing: uniform_trailing
          guidance_rescale: 0.7
          verbose: False
